spring.application.name=shatranj

spring.datasource.url=jdbc:postgresql://localhost:5432/shatranj
spring.datasource.username=postgres
spring.datasource.password=@Keziah14

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

